name: govulncheck
on:
  push:
    branches:
      - release-1.26-vngcloud-v2

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Scan for Vulnerabilities in Code
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.21.8
          go-package: ./...
